# Models

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

import datetime

import seaborn as sns

In [11]:
df_a_raw = pd.read_csv("../data/data_clean/accepted_2007_to_2018Q2.csv")
df_a_raw_copy = df_a_raw.copy() #for comaprison

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

## Data Prep

In [12]:
def display_df(df, nrows=10, ncols=None):
    with pd.option_context('display.max_rows', nrows, 'display.max_columns', ncols):
        display (df)
def print_row(df, row):
    for ctr,i in enumerate(df.iloc[row]):
        print (str(df.columns[ctr])+": "+str(i))

In [102]:
display_df(df_a_raw, 10)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,38098114,NaN,15000.0,15000.0,15000.0,60 months,12.39,336.64,C,C1,MANAGEMENT,10+ years,RENT,78000.0,Source Verified,Dec-2014,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,235xx,VA,12.03,0.0,Aug-1994,750.0,754.0,0.0,NaN,NaN,6.0,0.0,138008.0,29.0,17.0,w,0.00,0.00,17392.370000,17392.37,15000.00,2392.37,0.0,0.00,0.0000,Jun-2016,12017.81,NaN,Nov-2017,684.0,680.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,149140.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184500.0,NaN,NaN,NaN,5.0,29828.0,9525.0,4.7,0.0,0.0,103.0,244.0,1.0,1.0,0.0,47.0,NaN,NaN,NaN,0.0,1.0,4.0,1.0,2.0,8.0,5.0,9.0,4.0,6.0,0.0,0.0,0.0,4.0,100.0,0.0,0.0,0.0,196500.0,149140.0,10000.0,12000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,36805548,NaN,10400.0,10400.0,10400.0,36 months,6.99,321.08,A,A3,Truck Driver Delivery Personel,8 years,MORTGAGE,58000.0,Not Verified,Dec-2014,Charged Off,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,937xx,CA,14.92,0.0,Sep-1989,710.0,714.0,2.0,42.0,NaN,17.0,0.0,6133.0,31.6,36.0,w,0.00,0.00,6611.690000,6611.69,5217.75,872.67,0.0,521.27,93.8286,Aug-2016,321.08,NaN,Feb-2017,564.0,560.0,0.0,59.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,162110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19400.0,NaN,NaN,NaN,7.0,9536.0,7599.0,41.5,0.0,0.0,76.0,290.0,1.0,1.0,1.0,5.0,42.0,1.0,42.0,4.0,6.0,9.0,7.0,18.0,2.0,14.0,32.0,9.0,17.0,0.0,0.0,0.0,4.0,83.3,14.3,0.0,0.0,179407.0,15030.0,13000.0,11325.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,37842129,NaN,21425.0,21425.0,21425.0,60 months,15.59,516.36,D,D1,Programming Analysis Supervisor,6 years,RENT,63800.0,Source Verified,Dec-2014,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,658xx,MO,18.49,0.0,Aug-2003,685.0,689.0,0.0,60.0,NaN,10.0,0.0,16374.0,76.2,35.0,w,0.00,0.00,25512.200000,25512.20,21425.00,4087.20,0.0,0.00,0.0000,May-2016,17813.19,NaN,Dec-2017,704.0,700.0,0.0,74.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,42315.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21500.0,NaN,NaN,NaN,4.0,4232.0,324.0,97.8,0.0,0.0,135.0,136.0,7.0,7.0,0.0,7.0,60.0,7.0,60.0,1.0,3.0,4.0,3.0,12.0,16.0,5.0,18.0,4.0,10.0,0.0,0.0,0.0,2.0,91.4,100.0,0.0,0.0,57073.0,42315.0,15000.0,35573.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,37612354,NaN,12800.0,12800.0,12800.0,60 months,17.14,319.08,D,D4,Senior Sales Professional,10+ years,MORTGAGE,125000.0,Verified,Dec-2014,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,car,Car financing,953xx,CA,8.31,1.0,Oct-2000,665.0,669.0,0.0,17.0,NaN,8.0,0.0,5753.0,100.9,13.0,w,6673.54,6673.54,11207.670000,11207.67,6126.46,5081.21,0.0,0.00,0.0000,Dec-2017,319.08,Jan-2018,Dec-2017,629.0,625.0,0.0,36.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,261815.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5700.0,NaN,NaN,NaN,2.0,32727.0,0.0,103.2,0.0,0.0,16.0,170.0,21.0,16.0,5.0,21.0,17.0,1.0,17.0,1.0,3.0,5.0,3.0,5.0,1.0,5.0,7.0,5.0,8.0,0.0,0.0,0.0,0.0,76.9,100.0,0.0,0.0,368700.0,18007.0,4400.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,37662224,NaN,7650.0,7650.0,7650.0,36 months,13.66,260.20,C,C3,Technical Specialist,< 1 year,RENT,50000.0,Source Verified,Dec-2014,Charged Off,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,850xx,AZ,34.81,0.0,Aug-2002,685.0,689.0,1.0,NaN,NaN,11.0,0.0,16822.0,91.9,20.0,f,0.00,0.00,2281.980000,2281.98,704.38,339.61,0.0,1237.99,222.8382,Aug-2015,17.70,NaN,Oct-2016,559.0,555.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,64426.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18300.0,NaN,NaN,NaN,6.0,5857.0,332.0,93.2,0.0,0.0,137.0,148.0,8.0,8.0,0.0,17.0,NaN,3.0,NaN,0.0,1.0,4.0,1.0,4.0,12.0,4.0,8.0,4.0,11.0,0.0,0.0,0.0,2.0,100.0,100.0,0.0,0.0,82331.0,64426.0,4900.0,64031.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2004086,126133153,NaN,4375.0,4375.0,4375.0,36 months,14.08,149.70,C,C3,Machine Operator,10+ years,MORTGAGE,52000.0,Not Verified,Jan-2018,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,home_improvement,Home improvement,601xx,IL,33.72,0.0,Feb-1994,690.0,694.0,0.0,NaN,NaN,22.0,0.0,28116.0,49.2,41.0,w,3661.72,3661.72,1044.480000,1044.48,713.28,331.20,0.0,0.00,0.0000,Aug-2018,149.70,Sep-2018,Aug-2018,709.0,705.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,249.0,217780.0,1.0,2.0,0.0,2.0,18.0,22184.0,66.0,1.0,3.0,6844.0,56.0,57200.0,3.0,0.0,0.0,5.0,9899.0,17696.0,52.7,0.0,0.0,122.0,286.0,1.0,1.0,3.0,1.0,NaN,17.0,NaN,0.0,5.0,10.0,7.0,14.0,4.0,19.0,34.0,10.0,22.0,0.0,0.0,0.0,1.0,100.0,42.9,0.0,0.0,274690.0,50300.0,37400.0,33419.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2004087,125340736,NaN,12000.0,12000.0,11975.0,36 months,10.42,389.58,B,B3,Clerk,8 years,MORTGAGE,36000.0,Verified,Jan-2018,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,463xx,IN,11.10,1.0,May-1998,685.0,689.0,0.0,21.0,NaN,14.0,0.0,11648.0,43.6,18.0,f,9874.67,9854.10,2793.050000,2787.23,2125.33,667.72,0.0,0.00,0.0000,Aug-2018,400.00,Sep-2018,Aug-2018,724.0,720.0,0.0,21.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,191131.0,2.0,1.0,0.0,0.0,115.0,105786.0,NaN,3.0,6.0,3662.0,44.0,26700.0,1.0,0.0,1.0,6.0,14702.0,7510.0,46.0,0.0,0.0,185.0,235.0,0.0,0.0,1.0,15.0,NaN,11.0,NaN,1.0,3.0,6.0,4.0,4.0,5.0,12.0,12.0,6.0,14.0,0.0,0.0,1.0,3.0,94.1,50.0,0.0,0.0,172918.0,117434.0,13900.0,60818.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2004088,125551208,NaN,14000.0,14000.0,13975.0,36 months,13.59,475.71,C,C2,Manager,2 years,OWN,80000.0,Source Verified,Jan-2018,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,car,Car financing,900xx,CA,1.35,0.0,Jul-2007,660.0,664.0,1.0,31.0,NaN,11.0,0.0,1461.0,4.1,21.0,f,0.00,0.00,14662.947011,14636.76,14000.00,662.95,0.0,0.00,0.0000,May-2018,11646.39,NaN,Aug-2018,709.0,705.0,0.0,31.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,1461.0,1.0,0.0,0.0,1.0,17.0,0.0,NaN,1.0,2.0,1406.0,4.0,35300.0,2.0,0.0,2.0,3.0,162.0,28839.0,4.8,0.0,0.0,52.0,125.0,3.0,3.0,0.0,3.0,31.0,0.0,31.0,5.0,4.0,4.0,8.0,14.0,2.0,11.0,19.0,4.0,11.0,0.0,0.0,0.0,1.0,75.0,0.0,0.0,0.0,35300.0,1461.0,30300.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2004089,Total amount funded in policy code 1: 1741781700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004090,Total amount funded in policy code 2: 539397275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

We must clean the dataset. Many variables are categorical and need dummy variables created. Some numerical variables have strings attatched to them. Some variables we should drop entirely.

To start, we can drop `id` and `member_id`. We should also drop the last two rows as they are not meaningful.

In [76]:
df_a_raw = df_a_raw_copy.copy()

In [19]:
df_a_clean = df_a_raw.drop(df_a_raw.index[[-1,-2]])
df_a_clean = df_a_clean.drop(['id', 'member_id'], axis=1)

In [21]:
display_df(df_a_clean)

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,15000.0,15000.0,15000.0,60 months,12.39,336.64,C,C1,MANAGEMENT,10+ years,RENT,78000.0,Source Verified,Dec-2014,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,235xx,VA,12.03,0.0,Aug-1994,750.0,754.0,0.0,NaN,NaN,6.0,0.0,138008.0,29.0,17.0,w,0.00,0.00,17392.370000,17392.37,15000.00,2392.37,0.0,0.00,0.0000,Jun-2016,12017.81,NaN,Nov-2017,684.0,680.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,149140.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184500.0,NaN,NaN,NaN,5.0,29828.0,9525.0,4.7,0.0,0.0,103.0,244.0,1.0,1.0,0.0,47.0,NaN,NaN,NaN,0.0,1.0,4.0,1.0,2.0,8.0,5.0,9.0,4.0,6.0,0.0,0.0,0.0,4.0,100.0,0.0,0.0,0.0,196500.0,149140.0,10000.0,12000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,10400.0,10400.0,10400.0,36 months,6.99,321.08,A,A3,Truck Driver Delivery Personel,8 years,MORTGAGE,58000.0,Not Verified,Dec-2014,Charged Off,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,937xx,CA,14.92,0.0,Sep-1989,710.0,714.0,2.0,42.0,NaN,17.0,0.0,6133.0,31.6,36.0,w,0.00,0.00,6611.690000,6611.69,5217.75,872.67,0.0,521.27,93.8286,Aug-2016,321.08,NaN,Feb-2017,564.0,560.0,0.0,59.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,162110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19400.0,NaN,NaN,NaN,7.0,9536.0,7599.0,41.5,0.0,0.0,76.0,290.0,1.0,1.0,1.0,5.0,42.0,1.0,42.0,4.0,6.0,9.0,7.0,18.0,2.0,14.0,32.0,9.0,17.0,0.0,0.0,0.0,4.0,83.3,14.3,0.0,0.0,179407.0,15030.0,13000.0,11325.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,21425.0,21425.0,21425.0,60 months,15.59,516.36,D,D1,Programming Analysis Supervisor,6 years,RENT,63800.0,Source Verified,Dec-2014,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,658xx,MO,18.49,0.0,Aug-2003,685.0,689.0,0.0,60.0,NaN,10.0,0.0,16374.0,76.2,35.0,w,0.00,0.00,25512.200000,25512.20,21425.00,4087.20,0.0,0.00,0.0000,May-2016,17813.19,NaN,Dec-2017,704.0,700.0,0.0,74.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,42315.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21500.0,NaN,NaN,NaN,4.0,4232.0,324.0,97.8,0.0,0.0,135.0,136.0,7.0,7.0,0.0,7.0,60.0,7.0,60.0,1.0,3.0,4.0,3.0,12.0,16.0,5.0,18.0,4.0,10.0,0.0,0.0,0.0,2.0,91.4,100.0,0.0,0.0,57073.0,42315.0,15000.0,35573.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,12800.0,12800.0,12800.0,60 months,17.14,319.08,D,D4,Senior Sales Professional,10+ years,MORTGAGE,125000.0,Verified,Dec-2014,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,car,Car financing,953xx,CA,8.31,1.0,Oct-2000,665.0,669.0,0.0,17.0,NaN,8.0,0.0,5753.0,100.9,13.0,w,6673.54,6673.54,11207.670000,11207.67,6126.46,5081.21,0.0,0.00,0.0000,Dec-2017,319.08,Jan-2018,Dec-2017,629.0,625.0,0.0,36.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,261815.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5700.0,NaN,NaN,NaN,2.0,32727.0,0.0,103.2,0.0,0.0,16.0,170.0,21.0,16.0,5.0,21.0,17.0,1.0,17.0,1.0,3.0,5.0,3.0,5.0,1.0,5.0,7.0,5.0,8.0,0.0,0.0,0.0,0.0,76.9,100.0,0.0,0.0,368700.0,18007.0,4400.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,7650.0,7650.0,7650.0,36 months,13.66,260.20,C,C3,Technical Specialist,< 1 year,RENT,50000.0,Source Verified,Dec-2014,Charged Off,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,850xx,AZ,34.81,0.0,Aug-2002,685.0,689.0,1.0,NaN,NaN,11.0,0.0,16822.0,91.9,20.0,f,0.00,0.00,2281.980000,2281.98,704.38,339.61,0.0,1237.99,222.8382,Aug-2015,17.70,NaN,Oct-2016,559.0,555.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,64426.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18300.0,NaN,NaN,NaN,6.0,5857.0,332.0,93.2,0.0,0.0,137.0,148.0,8.0,8.0,0.0,17.0,NaN,3.0,NaN,0.0,1.0,4.0,1.0,4.0,12.0,4.0,8.0,4.0,11.0,0.0,0.0,0.0,2.0,100.0,100.0,0.0,0.0,82331.0,64426.0,4900.0,64031.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2004084,18000.0,18000.0,18000.0,36 months,10.42,584.37,B,B3,Beauty Advisor,10+ years,RENT,47000.0,Not Verified,Jan-2018,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,114xx,NY,15.37,0.0,Aug-1992,680.0,684.0,0.0,33.0,NaN,13.0,0.0,11362.0,39.0,29.0,w,12879.71,12879.71,6103.160000,6103.16,5120.29,982.87,0.0,0.00,0.0000,Aug-2018,632.00,Sep-2018,Aug-2018,689.0,685.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,20126.0,0.0,1.0,1.0,1.0,9.0,8764.0,67.0,1.0,5.0,6663.0,39.0,29200.0,0.0,1.0,3.0,6.0,1829.0,3800.0,51.0,0.0,0.0,79.0,304.0,8.0,8.0,0.0,15.0,77.0,3.0,33.0,0.0,5.0,10.0,9.0,11.0,8.0,10.0,21.0,6.0,11.0,NaN,0.0,0.0,2.0,90.0,20.0,0.0,0.0,42200.0,20126.0,19000.0,13000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2004085,6000.0,6000.0,6000.0,36 months,10.91,196.18,B,B4,Truck Driver,10+ years,MORTGAGE,50000.0,Source Verified,Jan-2018,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,038xx,NH,28.93,0.0,Jun-1997,690.0,694.0,0.0,58.0,NaN,11.0,0.0,6950.0,51.9,14.0,w,4981.14,4981.14,1369.620000,1369.62,1018.86,350.76,0.0,0.00,0.0000,Aug-2018,196.18,Sep-2018,Aug-2018,709.0,705.0,0.0,58.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,230614.0,0.0,1.0,1.0,1.0,9.0,18497.0,83.0,1.0,1.0,2257.0,71.0,13400.0,1.0,0.0,2.0,2.0,20965.0,5850.0,54.3,0.0,0.0,9.0,246.0,7.0,7.0,2.0,45.0,58.0,7.0,58.0,1.0,8.0,8.0,8.0,9.0,1.0,9.0,11.0,8.0,11.0,0.0,0.0,0.0,2.0,78.6,12.5,0.0,0.0,275650.0,25447.0,12800.0,22250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2004086,4375.0,4375.0,4375.0,36 months,14.08,149.70,C,C3,Machine Operator,10+ years,MORTGAGE,52000.0,Not Verified,Jan-2018,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,home_improvement,Home improvement,601xx,IL,33.72,0.0,Feb-1994,690.0,694.0,0.0,NaN,NaN,22.0,0.0,28116.0,49.2,41.0,w,3661.72,3661.72,1044.480000,1044.48,713.28,331.20,0.0,0.00,0.0000,Aug-2018,149.70,Sep-2018,Aug-2018,709.0,705.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,249.0,217780.0,1.0,2.0,0.0,2.0,18.0,22184.0,66.0,1.0,3.0,6844.0,56.0,57200.0,3.0,0.0,0.0,5.0,9899.0,17696.0,52.7,0.0,0.0,122.0,286.0,1.0,1.0,3.0,1.0,NaN,17.0,NaN,0.0,5.0,10.0,7.0,14.0,4.0,19.0,34.0,10.0,22.0,0.0,0.0,0.0,1.0,100.0,42.9,0.0,0.0,274690.0,50300.0,37400.0,33419.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2004087,12000.0,12000.0,11975.0,36 months,10.42,389.58,B,B3,Clerk,8 years,MORTGAGE,36000.0,Verified,Jan-2018,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,463xx,IN,11.10,1.0,May-1998,685.0,689.0,0.0,21.0,NaN,14.0,0.0,11648.0,43.6,18.0,f,9874.67,9854.10,2793.050000,2787.23,2125.33,667.72,0.0,0.00,0.0000,Aug-2018,400.00,Sep-2018,Aug-2018,724.0,720.0,0.0,21.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,191131.0,2.0,1.0,0.0,0.0,115.0,105786.0,NaN,3.0,6.0,3662.0,44.0,26700.0,1.0,0.0,1.0,6.0,14702.0,7510.0,46.0,0.0,0.0,185.0,235.0,0.0,0.0,1.0,15.0,NaN,11.0,NaN,1.0,3.0,6.0,4.0,4.0,5.0,12.0,12.0,6.0,14.0,0.0,0.0,1.0,3.0,94.1,50.0,0.0,0.0,172918.0,117434.0,13900.0,60818.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2004088,14000.0,14000.0,13975.0,36 months,13.59,475.71,C,C2,Manager,2 years,OWN,80000.0,Source Verified,Jan-2018,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,car,Car financing,900xx,CA,1.35,0.0,Jul-2007,660.0,664.0,1.0,31.0,NaN,11.0,0.0,1461.0,4.1,21.0,f,0.00,0.00,14662.947011,14636.76,14000.00,662.95,0.0,0.00,0.0000,May-2018,11646.39,NaN,Aug-2018,709.0,705.0,0.0,31.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,1461.0,1.0,0.0,0.0,1.0,17.0,0.0,NaN,1.0,2.0,1406.0,4.0,35300.0,2.0,0.0,2.0,3.0,162.0,28839.0,4.8,0.0,0.0,52.0,125.0,3.0,3.0,0.0,3.0,31.0,0.0,31.0,5.0,4.0,4.0,8.0,14.0,2.0,11.0,19.0,4.0,11.0,0.0,0.0,0.0,1.0,75.0,0.0,0.0,0.0,35300.0,1461.0,30300.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
#statistical functions

#gets ratio of NaNs for each column
def stats_NaN(df):
    df_stats = pd.DataFrame(index=[df.columns], columns=["NaN Ratio"])
    for col in df.columns:
        df_stats["NaN Ratio"][col] = df[col].isna().sum()/len(df) #NaN ratio
    return df_stats.sort_values(by=['NaN Ratio'])

#helps decide what to make dummies for and what to drop
def stats_unique(df, labels):
    df_counts = pd.DataFrame(index=labels,columns=['Unique Count'])
    for l in labels:
        df_counts['Unique Count'][l] = df[l].nunique()
    return df_counts

In [97]:
#helpful cleaning functions
def convert_percent(df, labels):
    for label in labels:
        df[label] = df[label].apply(lambda s: float(s.rstrip('%'))/ 100.0)
        
def convert_date(df, labels, frmt):
    for label in labels:
        df[label] = df[label].apply(lambda s: pd.to_datetime(s, format=frmt))
        
def convert_binary(df, labels):
    def to_bin(x, valid):
        if not np.isnan(x):
            if x == valid:
                return 1
            else:
                return 0
        return x #keeps NaNs
            
    for label in labels:
        #get first non NaN value in column
        valid = df[label].loc[df[label].first_valid_index()]
        df[label] = df[label].apply(lambda x: to_bin(x, valid))
def replace_NaNs(df, labels, fill_val):
    for label in labels:
        df[label].fillna(fill_val, inplace=True)

In [100]:
def subgrade_to_num(grade):
    if grade != None or not np.isnan(grade):
        print(grade)
        letter = grade[0]
        num = int(grade[1])
        num_grade = {
            'A':0,
            'B':1,
            'C':2,
            'D':3,
            'E':4,
            'F':5,
            'G':6
        }.get(letter)
        num_grade += (num-1)*0.2
        return num_grade
    else:
        return np.nan

In [90]:
df_a_raw['term'][0].strip()[0:2]

'60'

In [ ]:
def clean_df(df_raw, ratio_feats, date_feats, binary_feats, fix_nan_inf_feats, drop_feats, term="term"):
    df = df_raw.copy() #use and return a fresh copy as to not overwrite raw dataset
    convert_percent(df, ratio_feats)
    convert_date(df, date_feats)
    convert_binary(df, binary_feats)
    
    
    return df

In [24]:
dummies = ['']
df_a_clean['verification_status'].nunique()

3

In [38]:
stats_nan = stats_NaN(df_a_clean)

In [39]:
display_df(stats_nan,None)

                                              NaN Ratio
loan_amnt                                   1.34725e-05
fico_range_high                             1.34725e-05
disbursement_method                         1.34725e-05
hardship_flag                               1.34725e-05
revol_bal                                   1.34725e-05
initial_list_status                         1.34725e-05
out_prncp                                   1.34725e-05
out_prncp_inv                               1.34725e-05
total_pymnt                                 1.34725e-05
fico_range_low                              1.34725e-05
total_pymnt_inv                             1.34725e-05
total_rec_int                               1.34725e-05
total_rec_late_fee                          1.34725e-05
recoveries                                  1.34725e-05
collection_recovery_fee                     1.34725e-05
last_pymnt_amnt                             1.34725e-05
last_fico_range_high                        1.34725e-05
policy_code                                 1.34725e-05
application_type                            1.34725e-05
total_rec_prncp                             1.34725e-05
addr_state                                  1.34725e-05
last_fico_range_low                         1.34725e-05
issue_d                                     1.34725e-05
funded_amnt                                 1.34725e-05
installment                                 1.34725e-05
grade                                       1.34725e-05
sub_grade                                   1.34725e-05
home_ownership                              1.34725e-05
verification_status                         1.34725e-05
term                                        1.34725e-05
loan_status                                 1.34725e-05
int_rate                                    1.34725e-05
funded_amnt_inv                             1.34725e-05
url                                         1.34725e-05
debt_settlement_flag                        1.34725e-05
purpose                                     1.34725e-05
pymnt_plan                                  1.34725e-05
zip_code                                    1.39714e-05
annual_inc                                  1.54684e-05
pub_rec                                     2.79429e-05
open_acc                                    2.79429e-05
acc_now_delinq                              2.79429e-05
delinq_amnt                                 2.79429e-05
earliest_cr_line                            2.79429e-05
delinq_2yrs                                 2.79429e-05
total_acc                                   2.79429e-05
inq_last_6mths                              2.84419e-05
last_credit_pull_d                           5.0397e-05
tax_liens                                   6.58653e-05
chargeoff_within_12_mths                    8.58245e-05
collections_12_mths_ex_med                  8.58245e-05
dti                                         0.000595782
pub_rec_bankruptcies                         0.00069458
revol_util                                  0.000770425
last_pymnt_d                                 0.00108428
title                                         0.0116522
acc_open_past_24mths                          0.0249774
total_bc_limit                                0.0249774
total_bal_ex_mort                             0.0249774
mort_acc                                      0.0249774
num_bc_sats                                   0.0292487
num_sats                                      0.0292487
mths_since_recent_bc                          0.0350773
total_il_high_credit_limit                    0.0350798
tot_hi_cred_lim                               0.0350798
mo_sin_rcnt_tl                                0.0350798
tot_coll_amt                                  0.0350798
num_rev_tl_bal_gt_0                           0.0350798
num_tl_op_past_12m                            0.0350798
num_accts_ever_120_pd                         0.0350798
total_rev_hi_lim                              0.0350798
num_tl_90g_dpd_24m                            0.0350798
num_actv_bc_tl                                0.0350798
num_op_rev_tl                                 0.0350798
num_il_tl                                     0.0350798
tot_cur_bal                                   0.0350798
num_bc_tl                                     0.0350798
num_actv_rev_tl                               0.0350798
num_tl_30dpd                                  0.0350798
mo_sin_old_rev_tl_op                          0.0350803
mo_sin_rcnt_rev_tl_op                         0.0350803
num_rev_accts                                 0.0350803
avg_cur_bal                                   0.0351022
pct_tl_nvr_dlq                                0.0351566
bc_open_to_buy                                0.0357389
percent_bc_gt_75                               0.035959
bc_util                                       0.0362499
emp_length                                    0.0622941
mo_sin_old_il_acct                            0.0648719
emp_title                                     0.0661707
num_tl_120dpd_2m                               0.073635
mths_since_recent_inq                          0.131431
next_pymnt_d                                    0.42112
inq_fi                                         0.432194
max_bal_bc                                     0.432194
open_rv_24m                                    0.432194
open_rv_12m                                    0.432194
total_bal_il                                   0.432194
open_il_24m                                    0.432194
open_il_12m                                    0.432194
open_act_il                                    0.432194
total_cu_tl                                    0.432195
inq_last_12m                                   0.432195
open_acc_6m                                    0.432195
all_util                                       0.432271
mths_since_rcnt_il                             0.449512
mths_since_last_delinq                         0.506437
il_util                                        0.512996
mths_since_recent_revol_delinq                 0.667432
mths_since_last_major_derog                     0.73965
mths_since_recent_bc_dlq                       0.765925
mths_since_last_record                         0.836335
desc                                           0.937095
annual_inc_joint                               0.957016
dti_joint                                      0.957018
verification_status_joint                       0.95751
sec_app_collections_12_mths_ex_med             0.963348
sec_app_chargeoff_within_12_mths               0.963348
sec_app_num_rev_accts                          0.963348
sec_app_open_act_il                            0.963348
sec_app_open_acc                               0.963348
sec_app_mort_acc                               0.963348
sec_app_inq_last_6mths                         0.963348
sec_app_earliest_cr_line                       0.963348
sec_app_fico_range_high                        0.963348
sec_app_fico_range_low                         0.963348
revol_bal_joint                                0.963348
sec_app_revol_util                             0.963981
sec_app_mths_since_last_major_derog            0.987438
settlement_term                                0.993311
settlement_amount                              0.993311
settlement_date                                0.993311
settlement_status                              0.993311
debt_settlement_flag_date                      0.993311
settlement_percentage                          0.993311
hardship_type                                  0.997097
hardship_last_payment_amount                   0.997097
hardship_payoff_balance_amount                 0.997097
hardship_status                                0.997097
hardship_loan_status                           0.997097
hardship_dpd                                   0.997097
hardship_length                                0.997097
payment_plan_start_date                        0.997097
hardship_end_date                              0.997097
hardship_start_date                            0.997097
hardship_amount                                0.997097
deferral_term                                  0.997097
hardship_reason                                0.997097
orig_projected_additional_accrued_interest     0.997574

In [44]:
check_uniqes_list = ['emp_title','home_ownership','verification_status','loan_status','pymnt_plan',
                    'purpose','title','addr_state','application_type','disbursement_method',
                     'debt_settlement_flag','initial_list_status']
display(stats_unique(df_a_clean,check_uniqes_list))

                     Unique Count
emp_title                  479489
home_ownership                  6
verification_status             3
loan_status                     9
pymnt_plan                      2
purpose                        14
title                       63155
addr_state                     51
application_type                2
disbursement_method             2
debt_settlement_flag            2
initial_list_status             2

We see that `emp_title` and `title` have too many values to create dummies for. So we should drop them. We should likely keep `addr_state` information as that could be relevant.

In [101]:
df_a['verification_status'].unique()

array(['Source Verified', 'Not Verified', 'Verified', nan], dtype=object)

In [98]:
ratio_feats = ['int_rate','dti','dti_joint','bc_util','il_util','sec_app_revol_util']
date_feats = ['issue_d','earliest_cr_line','last_credit_pull_d','last_pymnt_d','next_pymnt_d']
binary_feats = ['pymnt_plan','application_type','disbursement_method','debt_settlement_flag	',
                'initial_list_status']
fix_nan_inf_feats = ['mths_since_last_delinq','mths_since_last_record','mths_since_recent_bc_dlq',
                 'mths_since_recent_inq','mths_since_recent_revol_delinq','mths_since_recent_inq']
drop_feats = ['url','desc', 'emp_title','title'] #other not useful features

In [94]:
stats_nan.loc[['mths_since_last_delinq']+['mths_since_last_record']]

                       NaN Ratio
mths_since_last_delinq  0.506437
mths_since_last_record  0.836335

In [75]:
stats_nan.loc[ratio_feats+date_feats+binary_feats]

                       NaN Ratio
disbursement_method  1.34725e-05
initial_list_status  1.34725e-05
application_type     1.34725e-05
issue_d              1.34725e-05
int_rate             1.34725e-05
pymnt_plan           1.34725e-05
earliest_cr_line     2.79429e-05
last_credit_pull_d    5.0397e-05
dti                  0.000595782
last_pymnt_d          0.00108428
bc_util                0.0362499
next_pymnt_d             0.42112
il_util                 0.512996
dti_joint               0.957018
sec_app_revol_util      0.963981

In [95]:
stats_nan.loc['max_bal_bc']

           NaN Ratio
max_bal_bc  0.432194